// Client/src/pages/customer/Home/components/ProductCard/ProductCard.tsx
import React from "react";
import formatNumberWithDots from "../../../../../utils/formatNumberWithDots";
import { ShoppingCartOutlined } from "@ant-design/icons";
import { message } from "antd";
import "./ProductCard.css";
import { CartService } from "../../../../../services";

type ProductCardProps = {
  productId: number;
  productImageUrl: string;
  productName: string;
  price: number;
  stock?: number;
  onClick?: () => void;
};

const ProductCard: React.FC<ProductCardProps> = ({
  productId,
  productImageUrl,
  productName,
  price,
  stock = 1,
  onClick
}) => {
  const handleAddToCart = async (e: React.MouseEvent) => {
    e.stopPropagation();

    try {
      await CartService.addProduct({
        productId,
        quantity: 1
      });
      message.success("Đã thêm sản phẩm vào giỏ hàng!");
    } catch (err) {
      console.error("Failed to add to cart:", err);
      message.error("Không thể thêm sản phẩm vào giỏ hàng");
    }
  };

  return (
    <div className="wrapper" style={{ cursor: onClick ? "pointer" : undefined }} onClick={onClick}>
      <div
        style={{
          background: `url(${productImageUrl}) no-repeat center`,
          width: "100%",
          paddingBottom: "100%",
          backgroundSize: "contain",
          position: "relative"
        }}
      >
        {stock > 0 && (
          <button
            onClick={handleAddToCart}
            style={{
              position: "absolute",
              top: "8px",
              right: "8px",
              borderRadius: "50%",
              border: "none",
              background: "transparent",
              cursor: "pointer"
            }}
          >
            <ShoppingCartOutlined />
          </button>
        )}
      </div>

      <div style={{ padding: "5px" }}>
        <p className="product-name">{productName}</p>
        <span
          style={{
            display: "block",
            color: "#ed8383",
            margin: "4px 0 2px",
            fontWeight: "bold",
            fontSize: "18px"
          }}
        >
          {formatNumberWithDots(price)}₫
        </span>
      </div>
    </div>
  );
};

export default ProductCard;

// frontend/src/components/ProductCard.vue
<script setup>
import HeartIcon from "@/icons/HeartIcon.vue";
import { formatNumberWithDots } from "@/utils/formatNumberWithDots";

const props = defineProps(["imageUrl", "brandName", "productName", "price"]);
</script>

<template>
  <div class="wrapper">
    <div
      class="image-container"
      :style="{
        background: `url(${props.imageUrl}) no-repeat center`,
      }"
      style="background-size: contain"
    />

    <el-button
      :icon="HeartIcon"
      circle
      style="position: absolute; top: 8px; right: 8px; background-size: cover"
    />

    <div style="padding: 5px">
      <h3 class="brand-name">
        {{ props.brandName }}
      </h3>
      <p class="two-line-ellipsis product-name" style="margin: 5px 0">
        {{ props.productName }}
      </p>
      <span
        style="
          display: block;
          color: #ed8383;
          font-weight: bold;
          font-size: 18px;
        "
        >{{ formatNumberWithDots(props.price) }}₫</span
      >
    </div>
  </div>
</template>

<style scoped>
.wrapper {
  position: relative;
  text-align: center;
  background-color: #fff;
  margin-bottom: 15px;
  transition: all 0.4s;
  border-radius: 2px;
  &:hover {
    cursor: pointer;
    box-shadow: rgba(0, 0, 0, 0.16) 0px 1px 4px;

    .product-name {
      transition: color 0.2s;
      color: #ed8383;
    }

    .brand-name {
      letter-spacing: 2px;
    }
  }
}

.brand-name {
  transition: letter-spacing 0.2s;
}

.product-name {
  transition: color 0.2s;
}

.image-container {
  width: 100%;
  padding-bottom: 100%;
  overflow: hidden;
  transition: transform 0.4s;

  &:hover {
    transform: scale(1.2);
  }
}
</style>
