// Client/src/pages/customer/Home/components/BenefitItem/BenefitItem.tsx
import React from "react";

type BenefitItemProps = {
  src: string;
  text: string;
};

const BenefitItem: React.FC<BenefitItemProps> = ({ src, text }) => {
  return (
    <div
      style={{
        color: "#fff",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        margin: "0 32px"
      }}
    >
      <img src={src} style={{ height: "40px", display: "block", margin: "12px 0" }} />
      <p>{text}</p>
    </div>
  );
};

export default BenefitItem;

// frontend/src/views/HomeView/components/BenefitItem.vue
<script setup>
const props = defineProps(["Icon", "text"]);
</script>

<template>
  <div
    style="
      color: #fff;
      display: flex;
      flex-direction: column;
      align-items: center;
      margin: 0 20px;
    "
  >
    <Icon style="height: 40px; display: block; margin: 12px 0" />
    <p>{{ props.text }}</p>
  </div>
</template>
